services:
  db:
    image: postgres:latest
    container_name: my_postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: MyTestApiDb
    ports:
      - "5435:5432" # Eğer 5432 doluysa yukarıda konuştuğumuz gibi 5433 yapabilirsin
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    container_name: my_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    restart: always